[package]
name = "bijective_map"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"
permutation_iterator = "0.1.2"

[[bench]]
name = "get"
harness = false